### ISSUE TITLE
Emotecraft + bendy-lib compatibility?

### ISSUE THREAD

**Issue by Vampzula** [FiguraMC/Figura#100]
Is it possible to make your own custom model and synchronize with Emotecraft + bendy-lib to support the bends of the model's bones?

Tnx google translate and thanks to anyone who will answer my stupid question...

**Comment by KitCat962** [comment]
Github Issues are for bug reports and feature requests. Help questions should go in the dedicated help channel in the FiguraMC discord.

Is this a question about mod support, or a request for mod support?

**Comment by Vampzula** [comment]
I apologize for writing in the wrong place. Initially, it was a question of whether it was possible to impose bone points on a custom model for Figura, so that emotions from Emotecraft would also bend the joints on the model. I know that emotecraft itself uses bendy-lib for more advanced animations using the bends of the player's model. Is it theoretically possible to implement this on a custom model from the same Blockbench? If this is not possible, then how about exploring adding bendy-lib support for Figura and creating animations in the blender editor? Maybe my idea is stupid, but I tried to explain the essence. Anyway, thanks for the answer!

**Comment by KitCat962** [comment]
So yea there is no emotecraft support built in to figura. To achieve their bendable limbs, they replace the vanilla model with a higher poly count one. 
Mesh deformation is actually really difficult to do in figura as blockbench has no concept of vertex groups. Not impossible though.
I've previously created a blender plugin that allows exporting a mesh object with it's vertex groups into a bbmodel and script file with the vertex group data. Actually deforming the mesh in-game is very instruction heavy (even though I've optimized it as much as possible) but if you want to check it out its available in the discord [here](https://discord.com/channels/1129805506354085959/1134183652419457154)
