### ISSUE TITLE
All addons are bricked due to the multi-jar packaging i think

### ISSUE THREAD

**Issue by sisby-folk** [FiguraMC/Figura#102]
Hey so we maintain an addon in [Switchy](https://github.com/sisby-folk/switchy/blob/1.19/compat/src/main/java/folk/sisby/switchy/client/SwitchyFiguraApi.java) and as far as i can tell the fabric+forge packaging of the jar breaks all java addons.

![image](https://github.com/FiguraMC/Figura/assets/55819817/badc7b67-44aa-4976-9672-ff4700bc6bef)

https://mclo.gs/nC7mrSC

tl;dr because the maven publication has `org/figuramc/figura/entries/FiguraAPI` but the jar has `fabric/org/figuramc/figura/entries/FiguraAPI` it just crashes on startup - far as I can figure it. Whatever's being done to the jar needs to be done to the publish too, or the 0.1.2 version on maven is just bad and should have that, etc.

continuation of a comment in https://github.com/sisby-folk/switchy/issues/50

**Comment by UnlikePaladin** [comment]
Hi yeah, we're aware of this, that's why this change has been rolled back for the next release, so everything should work fine once again when we release 0.1.3

**Comment by totallytavi** [comment]
Is there a version unaffected by this or will we have to wait for 0.1.3?

**Comment by KitCat962** [comment]
you can download the dev releases from the discord which separate fabric from forge. Or there are the github actions. Not a clean solution, but a solution none the less

**Comment by UnlikePaladin** [comment]
This is known and fixed on 0.1.3 development builds, we're not merging jars in the future anymore, so I'm closing this as completed
