### ISSUE TITLE
[1.20.1] Setting the vanilla model as invisible makes maps not visible with First Person Model mod

### ISSUE THREAD

**Issue by WereTech** [FiguraMC/Figura#103]
I don't know if this is something that I would have to fix myself, or if this is an issue with Figura or the other mod. Either way I don't know enough lua to adjust the model script to account for this. When holding a map, it will just show the map as an item and not the image it's supposed to represent. I need to have the player model invisible or it clashes with a lot of things.

Player model invisible
![2023-10-23_02 27 35](https://github.com/FiguraMC/Figura/assets/17415815/92e6b58a-8d90-4389-923a-8b6ecca1154a)

Player model not invisible
![2023-10-23_02 27 04](https://github.com/FiguraMC/Figura/assets/17415815/17c8d09c-a7ed-4737-8200-2448b6349a74)

**Comment by Covkie** [comment]
This can be worked around in script by enabling the arms(?) on the host when in first person.  Join our Discord linked in the `README` for further help.

This is technically is an incompatibility but as it is also *technically* user error (not utilizing Figura's scripting capability) I'll be closing this.
