### ISSUE TITLE
Figura's resetting my keybinds after every game restart

### ISSUE THREAD

**Issue by mosharky** [FiguraMC/Figura#110]
Disabling Figura solved the issue, I just don't know what it might be conflicting with.

**Comment by zlainsama** [comment]
I also encountered this.
I am using figura-0.1.2+1.20.1 with Forge 1.20.1 - 47.2.14.
This happens when I changed Figura's keybinds through it's settings. (changed action wheel button from B to V)
In the next game launch, all modded keybinds got reset to their defaults while vanilla keybinds stayed.

**Comment by DDunda** [comment]
I have also encountered this.

I'm using figura-0.1.2+1.20.1 with forge 47.2.17, and the issue appears to occur whenever any figura settings are changed. Deleting figura.json in /config/ resolves the issue, and disabling figura is not necessary.

**Comment by Beethoven-n** [comment]
why does the issue have a "fixed" label when it's still open and still a problem?

**Comment by KitCat962** [comment]
cause it is fixed in the repo. However, a stable release containing that fix hasnt been released. Dunno why it is still open.

**Comment by PoolloverNathan** [comment]
> cause it is fixed in the repo. However, a stable release containing that fix hasnt been released. Dunno why it is still open.

iirc the justification for not closing it was because the fix wasn't released yet.
