### ISSUE TITLE
crashing after multiple updatest to mods in this packw hen i download figura

### ISSUE THREAD

**Issue by hi4444** [FiguraMC/Figura#111]
crashing after multiple updatest to mods in this pack hen i download figura  here the pack it has everything add figura and try to launch but just to not if you do everytime it breaks it to where you gotta reimport pack on curseforge have to send link to medifire for it cause its to large other wise https://www.mediafire.com/file/yd80sf6yncaam2r/DerpMania-not+working+with+figura.zip/file

**Comment by KitCat962** [comment]
just send the crash report

**Comment by hi4444** [comment]
the thing is it doesnt give a crash report im pretty sure only logs

**Comment by KitCat962** [comment]
then give the log

**Comment by hi4444** [comment]
well it seems to have fixed itself after 2 more mods getting updates today for example essintals mod and Entity Model Features
so im just going to close this
