### ISSUE TITLE
Wearing certain modded armor w/ armor pivots crashes the game on Forge

### ISSUE THREAD

**Issue by TJT01** [FiguraMC/Figura#115]
## Description

Wearing certain modded armor pieces--such as Thermal Innovation's armor--crash the game when rendered using armor pivots.

## Repro. Steps

 1) Equip an avatar that uses armor pivots (see files below)
 2) Wear modded armor, such as Thermal Innovation's diving suit
 3) Look at yourself
 4) Crash

## Mods

 * Minecraft 1.18.2
 * Forge 40.2.15
 * Figura 0.1.2+1.18.2
 * Thermal Innovation 9.2.2 (adds armor which crashes w/ Figura)
 * Thermal Foundation 9.2.2 (req'd by Thermal Innovation)
 * CoFH Core 9.2.3 (req'd by Thermal Innovation and Thermal Foundation)

## Suggested Fix

Please use [`HumanoidArmorLayer#getArmorResource`](https://github.com/MinecraftForge/MinecraftForge/blob/b2c52b37a7e105259e5d5753b0933122a4b6e60c/patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch#L67C1-L67C149) instead of vanilla's method on Forge.

## Files

Crash report: [crash-2023-11-09_22.48.23-client.txt](https://github.com/FiguraMC/Figura/files/13315300/crash-2023-11-09_22.48.23-client.txt)
Avatar: [armor pivot.zip](https://github.com/FiguraMC/Figura/files/13315306/armor.pivot.zip)

**Comment by kcin2001** [comment]
try it on the newest dev builds on the discord, while it does not produce the same crash report as the usual its good to test there all the same

**Comment by TJT01** [comment]
Still crashes. [crash-2023-11-10_14.50.17-client.txt](https://github.com/FiguraMC/Figura/files/13322747/crash-2023-11-10_14.50.17-client.txt)
