### ISSUE TITLE
[Large Issue] Ability to see other player's items with Figura

### ISSUE THREAD

**Issue by python-nerd-3** [FiguraMC/Figura#120]
When viewing the permissions of someone, you can see the item they hold no matter what. This seems niche but it can be used to your advantage in several different scenarios. For example, you can see items that only certain roles have in a murder mystery gamemode. This can easily allow cheating without anyone noticing. Please create a patch to this or create a permission node to disable the feature.

**Comment by KitCat962** [comment]
The minecraft server itself syncs this information, so any cheat client will have access to this information. So while yes this could be implemented, if they are willing to cheat using Figura they are willing to use a cheat client to get that information regardless.

**Comment by python-nerd-3** [comment]
"cheat clients can do it so our normal client can too"

Not to be rude, but

**Comment by KitCat962** [comment]
I mean if you want to, speak to an actual dev about it. I'm just saying the common consensus regarding stuff like this so that you at least have an answer instead of "X closed this as not planned with no explanation"
