### ISSUE TITLE
[Quilt] [1.20.1] Figura causes crashes with other mods that add client-side commands

### ISSUE THREAD

**Issue by Silveere** [FiguraMC/Figura#121]
On Minecraft 1.20.1 with Quilt, Figura causes Minecraft to crash when entering client-side commands added by other mods into the chat. This seems to be caused by `ClientCommandSourceMixin.java` (idk what the underlying issue is since I know next to nothing about mod development, I just deleted it and it stopped crashing). Here are some examples that I've found trigger the crash:
| Mod | Condition |
|---|---|
|[ClientCommands](https://github.com/Earthcomputer/clientcommands)|Type `/cgetdata entity @s` and press enter. (possibly related: https://github.com/Earthcomputer/clientcommands/issues/423) |
|[Spark](https://github.com/lucko/spark)|Type `/sparkc `. The game crashes when pressing space. (related: https://github.com/lucko/spark/issues/370)|

Log: https://mclo.gs/BfuWrgR

**Comment by UnlikePaladin** [comment]
This is fixed on 0.1.3 beta builds, either update to those or don't use those mods in the meantime
