### ISSUE TITLE
crash when rendering GUI

### ISSUE THREAD

**Issue by cowardlycamper32** [FiguraMC/Figura#125]
on an instance with just figura, clicking on the figure button in the pause menu causes a crash on 1.18.2.
[crash-2023-11-26_14.29.07-client.txt](https://github.com/FiguraMC/Figura/files/13467090/crash-2023-11-26_14.29.07-client.txt)
[latest.log](https://github.com/FiguraMC/Figura/files/13467091/latest.log)

**Comment by Covkie** [comment]
This is a known bug and is fixed in dev release 0.1.3 pre2. Join our discord and navigate to [#dev-releases](https://discord.com/channels/1129805506354085959/1141418789423030342) to fix this
