### ISSUE TITLE
Third-party downloads disabled on CurseForge

### ISSUE THREAD

**Issue by Su5eD** [FiguraMC/Figura#132]
I've tried installing Figura in my userdev environment via CF maven today, but unfortunately that is not possible due to third-party downloads being [disabled](https://cflookup.com/901503). This is set despite Figura itself being open-source, licensed under the [LGPL license](https://github.com/FiguraMC/Figura/blob/da682437bc75d9093f9f642ebcf00f858283f64a/LICENSE), which allows redistribution freely. Please consider enabling third-party downloads on your project.

### Steps to reproduce
1. Add the [CurseMaven](https://cursemaven.com/) repository to your dev environment
2. Attempt to install Figura: `implementation(fg.deobf("curse.maven:figura-901503:4695287"))`
3. Receive an error
    `Caused by: org.gradle.internal.exceptions.DefaultMultiCauseException: Could not resolve curse.maven:figura-901503:4695287.`

**Comment by skyrina** [comment]
thanks for bringing this to our attention, i've enabled the toggle.
