### ISSUE TITLE
Backend does not advertise correct pre-release version

### ISSUE THREAD

**Issue by hibiii** [FiguraMC/Figura#146]
Hi, I'm on 0.1.2, and from a cursory look at the client code, everything about checking for updated versions should work.

However, the advertised pre-release version at `https://figura.moonlight-devs.org/api/version` is 0.1.2. I'm not asking "need pre-release now", but I have seen issues that refer to seemingly existing, but publicly inaccessible pre-release versions, for example 0.1.3-rc2 ([#72](https://github.com/FiguraMC/Figura/issues/76#issuecomment-1762963254)), 0.1.3-pre2 ([#113](https://github.com/FiguraMC/Figura/issues/113#issuecomment-1788733391), [#125](https://github.com/FiguraMC/Figura/issues/125#issuecomment-1826896138)). In one case, a link to a supposed pre-release version is behind an account gate.

Additionally, there's no mechanism in the client for the mod to complain about it being a newer version than advertised in the  selected channel, which would make these backend configuration errors obvious to maintainers.

Ordinarily I wouldn't mind this, but a crash is fixed with one of the mods I use in "0.1.3 development builds" ([#102](https://github.com/FiguraMC/Figura/issues/102#issuecomment-1819927691)), but there are none of such builds publicly available.

**Comment by KitCat962** [comment]
All the prerelease builds are available in the discord in the [dev-releases](https://discord.com/channels/1129805506354085959/1141418789423030342) channel.
0.1.3-rc2 and 0.1.3-pre2 are the same version, just an accidental naming mistake.

The mod does have a way to complain about versions, but it is not very noticeable. I definitly agree that there should be a more obvious version indicator (the "message of the day" that is currently broadcasting the release of 0.1.2 doesn't count)
![image](https://github.com/FiguraMC/Figura/assets/94943674/742cc041-4c5e-4fad-8b4c-e461dbf43351)

As for the backend version, Figura and it's backend are 2 separate systems, so someone probably got lazy when the 0.1.3 prereleases started dropping. ~~I'll post a message in the [development-chat](https://discord.com/channels/1129805506354085959/1129815148190761081) about it.~~

**Comment by skyrina** [comment]
the backend now returns the correct prerelease version

**Comment by ElectricDaFearox** [comment]
>  ~I'll post a message in the [development-chat](https://discord.com/channels/1129805506354085959/1129815148190761081) about it.~

I am 4 parallel universes ahead of you

**Comment by Cynosphere** [comment]
> All the prerelease builds are available in the discord

GitHub releases have pre-release tags and don't show up as the main release. Why are you contributing to [information voiding](http://ascii.textfiles.com/archives/5509)? Why should I have to have a second Discord account dedicated to joining gatekept resources like this?

Please do better than dying on this hill.

**Comment by skyrina** [comment]
we are still working on our next version of the backend, which will include a proper version system.
future prerelease versions will also be published to github from now on, but modrinth and curseforge will remain only for full releases.

**Comment by UnlikePaladin** [comment]
> > All the prerelease builds are available in the discord
> 
> GitHub releases have pre-release tags and don't show up as the main release. Why are you contributing to [information voiding](http://ascii.textfiles.com/archives/5509)? Why should I have to have a second Discord account dedicated to joining gatekept resources like this?
> 
> Please do better than dying on this hill.

No one is dying on a hill and no one was contributing to "voiding" on purpose, all those pre releases that we released were also available here through actions, we are all volunteers on this mod we do not get paid, nor do we gatekeep, so please don't go around demanding things, there are nicer ways to ask for things than just telling people to do better, so don't go looking for drama where there is none, like skyrina said, we'll publish future pre-releases here as well, but please be kind to others. Hope you understand and have a nice day.

**Comment by Cynosphere** [comment]
> and no one was contributing to "voiding" on purpose
> nor do we gatekeep

From what I've been told there's also development resources and other things like themes that are only available on the Discord as well, so it's more than just pre-release versions.

> but please be kind to others.

How am I not? I'm being civil about the whole ordeal opposed to going off the deep end with swear words every other word. Sorry you read it in an aggressive tone.

**Comment by UnlikePaladin** [comment]
> > and no one was contributing to "voiding" on purpose
> > nor do we gatekeep
> 
> From what I've been told there's also development resources and other things like themes that are only available on the Discord as well, so it's more than just pre-release versions.
> 
> > but please be kind to others.
> 
> How am I not? I'm being civil about the whole ordeal opposed to going off the deep end with swear words every other word. Sorry you read it in an aggressive tone.

Your "do better" comment read as quite passive aggressive, I'm sorry if that's not what you intended and we misinterpreted it. You're always free to join the Discord, but I can assure you we don't host any official extra development resources on it, the Discord just happens to be where the majority of our community interacts because we simply don't have elsewhere to do so, so they share their own avatars, themes and forks in it, we are looking into allowing users to publish stuff from within the game and access it within the game in the future but that's still a far off goal.

**Comment by Cynosphere** [comment]
> You're always free to join the Discord

This is so tonedeaf its not even funny. Have a good day.

**Comment by KitCat962** [comment]
> From what I've been told there's also development resources

Most "development resources" are actually not on the discord. 
There are (poor but functional) documentation provided by the mod itself via the in-game `/figura docs` command. These docs are also available via the fan site [FIGS](https://applejuiceyy.github.io/figs/). Additionally, Figura has an [external wiki](https://wiki.figuramc.org/) (though I do agree we need more people working on it)
The only other resources is the Hellp channel, which makes zero sense to move to github, and we dont have anywhere else to put it.

**Comment by UnlikePaladin** [comment]
> > You're always free to join the Discord
> 
> This is so tonedeaf its not even funny. Have a good day.

What people share on the Discord is user created content, not official, if you want to access that, you have to join it, simple as that, it's where the community exists, we literally can't make users publish their content elsewhere, unless they want to, which some people do on sites like Planet MC. Anyway, I hope you have a good day as well
