### ISSUE TITLE
Advertised website for downloading Figura pre-release versions does not host them.

### ISSUE THREAD

**Issue by hibiii** [FiguraMC/Figura#148]
The client mod notifies me that there is a pre-release version available, and it correctly directs me to the Modrinth versions page for Figura, but the advertised version (0.1.3-rc3) is not listed at <https://modrinth.com/mod/figura/versions>. I do not have any filters set that would hide any versions, betas or alphas.

**Comment by UnlikePaladin** [comment]
they used to be only on our discord but we're uploading them to GitHub soon, but they will not go on Modrinth or CF; only stable builds release there
