### ISSUE TITLE
Armor issue

### ISSUE THREAD

**Issue by Obsidron** [FiguraMC/Figura#162]
Screenshot: https://github.com/FiguraMC/Figura/assets/155651350/ec8d0173-19d8-4c0a-827b-b7d6b7e5beca

This happens with all types of armor from all mods. This does not happen with vanilla armor

Forge: 47,2.0
Figura version: 0.1.2+1.20.1
Minecraft version: 1.20.1

**Comment by UnlikePaladin** [comment]
This should no longer happen on 0.1.3 rc.4, armors that use entirely custom models still don't work but the missing textures should be fixed now
