### ISSUE TITLE
Class not found on ATM9

### ISSUE THREAD

**Issue by Octelly** [FiguraMC/Figura#163]
I've been playing a modified version of [ATM9](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9)-[0.2.36](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5016013) (MC 1.20.1, Forge 47.2.19) recently, one of the modifications being Figura. It used to work fine with Figura, but I ended up disabling it while troubleshooting something and I have decided to enable it again after a couple modpack updates.

It's complaining about [``java.lang.ClassNotFoundException: org.luaj.vm2.lib.VarArgFunction`` (link to full log)](https://mclo.gs/LCEZBCV#L15047). No idea why this would happen, I doubt it's an incompatibility with any of the other mods that sport LUA scripting as well (only one I can think of is ComputerCraft anyway).

I'm hoping the log can help figure out what happened and decide what's the cause of the issue and whether it's Figura's fault or not. Figura is such an essential mod in my eyes nowadays that it causing a crash is a major bummer.

([a list of mods is included in the log](https://mclo.gs/LCEZBCV#L137))

**Comment by Octelly** [comment]
*correction: Figura does not crash the game, that is caused by another mod

**Comment by UnlikePaladin** [comment]
this is a Forge issue, not ours, which has been fixed on newer versions but they didn't back port, it's something related to class loading, anyway the class does exist and this doesn't actually cause problems other than log spam and we sadly can't do much about it

**Comment by Octelly** [comment]
Alright, thanks for the response :+1:
