### ISSUE TITLE
ClickEvent in chat causes crash

### ISSUE THREAD

**Issue by DBTDerpbox** [FiguraMC/Figura#164]
Currently using `figura-0.1.3-pre.3-1.20.4-fabric-mc.jar` from the pre-releases found on discord

When clicking on a ClickEvent in chat, the game will crash if Figura is installed. This issue was not present in 1.20.1 however I haven't updated my 1.20.1 instance in a while

You can test this yourself with `/tellraw @p {"text":"Click here","color":"blue","clickEvent":{"action":"run_command","value":"/give @s diamond"}}`

[latest.log](https://github.com/FiguraMC/Figura/files/13926830/latest.log)

**Comment by UnlikePaladin** [comment]
yeah Mojang reworked Click Events in 1.20.4 and I messed up with the port, my bad

**Comment by DBTDerpbox** [comment]
seems to work fine in [rc4](https://github.com/FiguraMC/Figura/releases/tag/0.1.3-rc.4) now

**Comment by UnlikePaladin** [comment]
Yeah, triple checked it worked before publishing rc.4!
