### ISSUE TITLE
Animations don't work correctly if BadOptimizations mod is installed

### ISSUE THREAD

**Issue by CerbonXD** [FiguraMC/Figura#173]
Basically this is how it should work:

https://github.com/FiguraMC/Figura/assets/84386993/f287cf52-ab37-4ab9-a563-af3e766fe50f

And this is how it works when `BadOptimizations` mod is installed

https://github.com/FiguraMC/Figura/assets/84386993/e7688015-d486-4e93-9da9-75202723ed83

Everything was tested in a new instance with only `Figura` and `BadOptimizations` mod installed. Note that script animations work fine, only animations from BlockBench doesn't, in this case my wings. The other animations were made using `SquishAPI`.

Figura version: 0.1.2
BadOptimizations version: 1.6..3

**Comment by x-yingcan-x** [comment]
seems fixed in BadOptimizations v2.0.0

**Comment by UnlikePaladin** [comment]
I was not aware they fixed it on their side, neat, closing this
