### ISSUE TITLE
Feature request: Custom event registration

### ISSUE THREAD

**Issue by alekso56** [FiguraMC/Figura#177]
ok, lets say i have a class implementing FiguraAPI 
```java
    @LuaWhitelist
    @LuaFieldDoc("myAPI.myCustomEvent")
    public static final LuaEvent myCustomEvent = new LuaEvent();
 ```
i want to be able to call that event on the java side
```java
   myCustomEvent.callOrSomething(varargs);
```
 and listen on the lua side
```lua
function myAPI.myCustomEvent()
    log("IM CUSTOM!")
end
```
just an example, but badly implemented. you can make events api be the hub instead of an external class from another mod.

**Comment by PoolloverNathan** [comment]
@alekso56 Adding functions via assignment merely requires defining `__newindex` for your addon; you can then either use a switch-case (fast for a few events) or reflection (what EventsAPI uses) and register the event there. I'll see if event dispatching is also similarly easy.

**Comment by UnlikePaladin** [comment]
> @alekso56 Adding functions via assignment merely requires defining `__newindex` for your addon; you can then either use a switch-case (fast for a few events) or reflection (what EventsAPI uses) and register the event there. I'll see if event dispatching is also similarly easy.

They're referring to something different and I already added an API for what they want

**Comment by alekso56** [comment]
https://github.com/FiguraMC/Figura/blob/44390bcd5379ddf10b126b832d9ed6b922fe7546/common/src/main/java/org/figuramc/figura/lua/api/event/EventsAPI.java#L119
Maybe im misunderstanding but wouldn't using "." in this instance refer to a table making the API useless in lua, if calling from events api?
ie events.MyAPI.MyEvent()
what's the intended call method?
@UnlikePaladin

**Comment by PoolloverNathan** [comment]
> https://github.com/FiguraMC/Figura/blob/44390bcd5379ddf10b126b832d9ed6b922fe7546/common/src/main/java/org/figuramc/figura/lua/api/event/EventsAPI.java#L119
> 
> Maybe im misunderstanding but wouldn't using "." in this instance refer to a table making the API useless in lua, if calling from events api?
> ie events.MyAPI.MyEvent()
> what's the intended call method?

@alekso56 You could do `events["MyAPI.MyEvent"]`, but I agree that that seems awkward.
