### ISSUE TITLE
Cloud: Disconnected, Reason: failed to verify

### ISSUE THREAD

**Issue by MrBaska** [FiguraMC/Figura#179]
How to fix: Cloud: Disconnected, Reason: failed to verify
Figura 1.18.2, server
![изображение](https://github.com/FiguraMC/Figura/assets/124176033/5f5c7732-0489-4f71-afec-662133db0324)

**Comment by KitCat962** [comment]
Failed to verify means that either your multiplayer session has expired, or you are not using a valid minecraft account.
The backend/cloud only accepts connections from accounts that can be verified.
