### ISSUE TITLE
Emoji issue

### ISSUE THREAD

**Issue by Lemonnik6484** [FiguraMC/Figura#181]
The problem is that emoji :51: breaking things like timestamps
so it will be nice to change the emoji name to something like   : alien :

Image from mod "chat patches" that shows timestamps ![image.png](https://github.com/FiguraMC/Figura/assets/74058717/d0028fe7-2efe-44e8-84b5-1029e46817f2)

**Comment by Slymeball** [comment]
Yeah, we've been contemplating this for a *long* time. I'm gonna go ahead and make a PR for removing the :51: alias rq

**Comment by Slymeball** [comment]
[This has been fixed now](https://github.com/FiguraMC/Assets/pull/60) and should make its way to clients soon! Make sure to press the "Redownload Assets" button in settings in a few minutes to receive the changes.
