### ISSUE TITLE
The custom model is reset after each re-entry to the world/server

### ISSUE THREAD

**Issue by Iarkont** [FiguraMC/Figura#184]
Every time you re-enter the world or the server, the custom model is reset and you have to enable it in the settings every time. I'm using the Fabric 1.20.1 and, of course, with a license.

**Comment by KitCat962** [comment]
If you are talking about the avatar, Figura downloads the avatar from the backend when joining a world.
Upload your avatar to have it equipped whenever you load into a world.

I'm aware that the backend is not entirely stable right now, so you might just have to deal with it until a new backend is developed that can handle the stress
![image](https://github.com/FiguraMC/Figura/assets/94943674/3c4b189f-7b0f-4606-876c-a77ba5442720)
