### ISSUE TITLE
[1.20.1] [Forge] Incompatibility Render Thread Crash with Controlling Mod

### ISSUE THREAD

**Issue by TimmyChips** [FiguraMC/Figura#190]
Hi,
After trying to add the mod Controlling to my Minecraft Forge mod list, the game will immediately crash on startup. I think Controlling is the one causing the crash, however, I see a couple of other mods in the crash report. I have tried removing these other mods, but the game will still crash until you remove Controlling. I have also tried the release candidates for Figura 0.1.3 with no luck.

I am not sure if this crash occurs on Fabric.

Here are the log files:
[crash-2024-02-26_13.33.47-client.txt](https://github.com/FiguraMC/Figura/files/14409963/crash-2024-02-26_13.33.47-client.txt)
[latest.log](https://github.com/FiguraMC/Figura/files/14409964/latest.log)

**Comment by KitCat962** [comment]
According to the crash report the problem mod is REI. Are you sure that the issue is Controlling+Figura?

**Comment by TimmyChips** [comment]
Looking at the report it appears the potential mods causing the crash are potentially REI, the Physics mod, Balm, and maybe a couple others I didn't catch in there. However, removing any of those mods doesn't seem to prevent the crash on startup. It's odd that Controlling is crashing, maybe it's a combination of a few mods? Not sure, since on another (solved) issue on this Github, that person said they had Controlling and had no crash related to that mod. I'll see if I can comb through the mods one-by-one at some point and see if any other mod is causing the issue.

EDIT: It appears the cause of the crash was not the mods aforementioned, but rather a dependency mod for Controlling missing! Ah, it's always the little things that slip by. Glad it was not Figura that was causing the issue. Marking this as closed!
