### ISSUE TITLE
Cloud disconnected, Reason: Unknown!

### ISSUE THREAD

**Issue by BelkaBoi** [FiguraMC/Figura#211]
So I get the error in the title, mc ver 1.20.4, mod ver 1.6.17
All the mods installed: 
![image](https://github.com/FiguraMC/Figura/assets/108747883/fea8a7e7-a683-4d2e-81ff-cd800be281da)

**Comment by PoolloverNathan** [comment]
The cloud is down; wait or check the [Cloud Issues Masterpost](https://discord.com/channels/1129805506354085959/1228805619746603008).
