### ISSUE TITLE
incompatibility crash with oculus

### ISSUE THREAD

**Issue by mryeeterson** [FiguraMC/Figura#212]
normal boot to menu without oculus: https://mclo.gs/zayEkMJ 
crash with oculus: https://mclo.gs/PAet4yz
launcher: prism launcher
modpack: [create perfect world](https://www.curseforge.com/minecraft/modpacks/create-perfect-world)

**Comment by frostproto27** [comment]
this is a known issue, and is a problem on oculus's side
read #176
