### ISSUE TITLE
Custom avatar server support?

### ISSUE THREAD

**Issue by IntelMiner** [FiguraMC/Figura#227]
### Request Description

Hi all,

My roommates have been playing Minecraft and are interested in using this mod. However they've complained there's a 100KB limit on uploading files(?) 

Since they're playing on a local LAN they've asked if there's any way I can run a "local server" to store the uploaded data with instead. 

I had a quick look around online but did not find any relevant results, so I figured I would ask over here.

Thank y'all in advance!

**Comment by TheZoidMaster** [comment]
**Based on what I've heard in the Discord**, the only way to do this as of now would be to completely reverse-engeneer the backend. However when the new backend version releases (somewhat soon i think), it will be open source so people can run their own.

**Comment by IntelMiner** [comment]
Fair enough. Is there any progress tracker on the new backend anywhere? Something I can give my roommates to keep them in the loop

**Comment by TheZoidMaster** [comment]
Not that I'm aware of, no.

**Comment by PoolloverNathan** [comment]
@shiroyashik does your backend impl support Mojang auth? (or trustmebro (aka no) auth, since this is lan with friends)

**Comment by shiroyashik** [comment]
> @shiroyashik does your backend impl support Mojang auth? (or trustmebro (aka no) auth, since this is lan with friends)

the problem is that Figura requires an SSL connection, which makes it difficult to set up, and it won't work without the Internet either, since a connection to the Mojang or ElyBy server is required to verify the "license".

**Comment by shiroyashik** [comment]
> @shiroyashik does your backend impl support Mojang auth? (or trustmebro (aka no) auth, since this is lan with friends)

the problem is that Figura requires an SSL connection, which makes it difficult to set up, and it won't work without the Internet either, since a connection to the Mojang or ElyBy server is required to verify the "license".

**Comment by shiroyashik** [comment]
@IntelMiner I updated [Sculptor](https://github.com/shiroyashik/sculptor) a bit today, now it still has a public server, if you want you can use it, the limitation is not so cruel there.

**Comment by IntelMiner** [comment]
@shiroyashik Ooh! I shall take a look. Thank you!!
