### ISSUE TITLE
[1.16.5] [Forge] Crash when trying to sleep in a bed

### ISSUE THREAD

**Issue by ShucklesDaPony** [FiguraMC/Figura#259]
### Bug Description

Trying to sleep in a bed immediately crashes the game

### Reproduction Steps

1.) Right click bed to sleep at night
2.) Immediate crash, not even the animation for laying in bed happens

### Log File

[latest.log](https://github.com/user-attachments/files/16970693/latest.log)

**Comment by UnlikePaladin** [comment]
Could you try the 0.1.5 Release Candidate 2 version, it's here on the GitHub and on our discord, it should have fixed this

**Comment by ShucklesDaPony** [comment]
Yeah it's fixed thank you
Sorry didn't notice the build
