### ISSUE TITLE
Change license from "LGPL- 2.1" to "LGPL- 2.1-or-later"

### ISSUE THREAD

**Issue by HappyRespawnanchor** [FiguraMC/Figura#265]
LGPL 2.1-or-later allows programs using LGPL 3.0 (or later) to also use Figura's code. It can make Figura's code more widely used.

**Comment by TheBunnyMan123** [comment]
While I support this, iirc everyone who ever contributed code will have to agree (as long as their code still exists in this). 

Speaking of, I am fine if my code gets relicensed

**Comment by HappyRespawnanchor** [comment]
Getting all contributors to agree is really a difficult thing to do...

**Comment by PoolloverNathan** [comment]
Can this be a PR so users can mark it as approved? iirc PRs also let you request reviews from all contributors

**Comment by lexize** [comment]
> While I support this, iirc everyone who ever contributed code will have to agree (as long as their code still exists in this).
> 
> Speaking of, I am fine if my code gets relicensed

Yeah this is main problem and what basically makes it impossible, because _the person_ and _the other person_ contributed to Figura too, so we would need their agreement, which is, in fact, impossible.

**Comment by Covkie** [comment]
certain past contributors are unlikely to agree
