### ISSUE TITLE
[1.21.1forge/fabric 0.1.5rc3]An error occurred during the playback of the custom model's animation.

### ISSUE THREAD

**Issue by OvOla2** [FiguraMC/Figura#271]
### Bug Description

The error shown in the image occurred when pressing the 'G' key to play the custom model's animation.
![Screenshot_20241114_233903](https://github.com/user-attachments/assets/7016ffcf-f7f3-4c69-b5b7-2a3a4a487568)
But this  animation plays normally on version 1.20.4fabric-figura0.1.4

### Reproduction Steps

1. Install Figura0.1.5rc3 on Minecraft 1.21.1
2. Download and install this avatar
(https://github.com/Gakuto1112/FiguraBlueArchiveCharacters/releases/download/v1.9.6/Izuna.zip)
4. Enter the game, load the corresponding avatar, press F5 to switch perspectives, press B to bring up the wheel menu and change outfits.
![2024-11-15_00 04 59](https://github.com/user-attachments/assets/bdb17b93-a40c-43ed-89fa-57118d7be107)
5. Press the G key.

### Log File

[latest.log](https://github.com/user-attachments/files/17751648/latest.log)

**Comment by penguinencounter** [comment]
That shader was removed in **24w11a** (1.20.5), according to [misode/mcmeta](https://github.com/misode/mcmeta):

[diff of assets](https://github.com/misode/mcmeta/commit/9d3ee4cced7b202cb748340db76cf63745cb6c8a#diff-b7fd1849b49fe57bf02da318ba35518d87fbcfbba3155661ab264f359337f665)

**Comment by OvOla2** [comment]
> That shader was removed in **24w11a** (1.20.5), according to [misode/mcmeta](https://github.com/misode/mcmeta):
> 
> [diff of assets](https://github.com/misode/mcmeta/commit/9d3ee4cced7b202cb748340db76cf63745cb6c8a#diff-b7fd1849b49fe57bf02da318ba35518d87fbcfbba3155661ab264f359337f665)

### 
So is this an issue with the Minecraft base game?

Maybe I should report this issue to the avatar's creator.
