### ISSUE TITLE
Custom Fonts in Nameplates get rerendered in the default font. (0.1.5-rc3+1.21) (using MC 1.21.1)

### ISSUE THREAD

**Issue by Trioplane** [FiguraMC/Figura#275]
### Bug Description

When you use custom fonts in your /team prefix or suffixes, Figura rerenders the font again in `minecraft:default`. This only occurs on the in-world nameplates.

**Expected Behavior**: (Vanilla)
![image](https://github.com/user-attachments/assets/7106ee82-9d6c-498d-8244-73f81a6f7d98)

**Observed Behavior**: (Figura 0.1.5-rc3+1.21)
![image](https://github.com/user-attachments/assets/fb718cca-1a0a-4ce1-b2b8-deebacc17b50)

### Reproduction Steps

**Step 1**: 
 - Get or make a resource pack with custom fonts.
 
**Step 2**: 
 - Make a team by doing `/team add TEAM_NAME "Team name"`
 
**Step 3**: 
 - Modify its prefix/suffix with the custom font:
```mcfunction
team add TEST "test"
team modify TEST prefix {"text":"A","font":"ns:my_custom_font"}
team join TEST @s 
```

**Step 4**: Look at your nameplate via FreeCam, Figura Settings, or getting another player. After that, exit minecraft and disable Figura and join back to see the expected results.

### Log File

Not Applicable, No warnings/errors/info found.

**Comment by UnlikePaladin** [comment]
This is already fixed and please do not open bug reports for test builds
