### ISSUE TITLE
Feature Request: Disable Discord nag

### ISSUE THREAD

**Issue by hibiii** [FiguraMC/Figura#35]
I don't use Discord a lot for Minecraft purposes anymore, and I'd rather have an option to disable the "Join our new Discord server" nag. In my case, I notice it more because i restart my game very often, and don't have long sessions.

I did take a cursory look around the repository to try and find where in the code the nag is defined and add a toggle there, but I didn't find even the translation string. Is this a server-sided nag?

I did notice that there's a badge for contest winners, which leads me to think about categories for server notifications, like differentiating service announcements and promotional notifications, like the Discord nag, if this is the case then I'd suggest a client sided config for server side notices, as I'd want to be notified of service outages but disregard contest notices.

**Comment by ElectricDaFearox** [comment]
Hi there! Sorry about that, the backend announce was used to guide people to our new discord server due to the previous owner deleting it. Sorry if it was a bother!
