### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by Nobody48213** [FiguraMC/Figura#5]
I was banned from the new figura server for no reason?

**Comment by Nobody48213** [comment]
I only put the error here since I don't know where else to

**Comment by skyrina** [comment]
heya, feel free to contact me on discord at `skyrina.dev` or on email at sorryu02@gmail.com and i'll let you know what's up. i'll delete this issue in a few days (if i even can)

**Comment by Nobody48213** [comment]
> heya, feel free to contact me on discord at `skyrina.dev` or on email at [sorryu02@gmail.com](mailto:sorryu02@gmail.com) and i'll let you know what's up. i'll delete this issue in a few days (if i even can)
I added you

**Comment by Nobody48213** [comment]
I added you
