### ISSUE TITLE
semi-frequent crash

### ISSUE THREAD

**Issue by kcin2001** [FiguraMC/Figura#50]
with seemingly no cause i semi frequently crash in both multiplayer and more rarely singleplayer
attached is the latest instance of it but i have like 20 of these, always the same error
[crash-2023-08-02_12.54.23-client.txt](https://github.com/FiguraMC/Figura/files/12244160/crash-2023-08-02_12.54.23-client.txt)

**Comment by KabanFriends** [comment]
This happens to me as well
For me it frequently happens in Multiplayer

**Comment by purpledeni** [comment]
Same for me

**Comment by KitCat962** [comment]
from what I can tell from the crash report, someone forgot to do an avatar null check when rendering players offscreen

**Comment by UnlikePaladin** [comment]
Will look into it

**Comment by KabanFriends** [comment]
Downgrading to Sodium 0.4.10 fixes the crash
So this is a Figura's incompatibility with Sodium 0.5.0

**Comment by kcin2001** [comment]
its definately not just sodium as i lack that mod
