### ISSUE TITLE
(1.19.2/forge) Crash on start up. Figura blaming oculus 

### ISSUE THREAD

**Issue by Thspooks** [FiguraMC/Figura#59]
https://pastebin.com/gT7sGByP - crash 
https://pastebin.com/00jqgLvx- full modlist 
Figura is blaming oculus, but i feel like its totally different thing causing it.
clearing configs used to help, but not it doesnt helps at all and im out of ideas how to fix it. If i missed something, ill give more info gladly

**Comment by Thspooks** [comment]
nvm it was missing a library 💀  But still, kind of weird its blaming figura and oculus... charms of forge ig

**Comment by Mirage-Panda** [comment]
> nvm it was missing a library 💀 But still, kind of weird its blaming figura and oculus... charms of forge ig

What library was it missing? I have he same issue

**Comment by Hirune30** [comment]
My problem is similar, I removed Oculus and Figure worked normally, I use 1.20.1 and Oculus 1.6.15.a /figure 0.1.4

**Comment by KitCat962** [comment]
> My problem is similar, I removed Oculus and Figure worked normally, I use 1.20.1 and Oculus 1.6.15.a /figure 0.1.4

Latest versions of oculus are strictly incompatible with figura due to their own fault. You can find more information here https://github.com/Asek3/Oculus/issues/548

**Comment by Hirune30** [comment]
I just reviewed it, it's a shame 😢
