### ISSUE TITLE
1.18.2 Fabric, keeps shutting down the game after clicking on the icon in the escape menu

### ISSUE THREAD

**Issue by Chamelllemon** [FiguraMC/Figura#76]
It does that through curseforge app, but works through tlauncher
Error message:
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.renderScrollBar(BackendMotdWidget.java:153)
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.renderDecorations(BackendMotdWidget.java:175)
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.method_25359(BackendMotdWidget.java:106)
	at net.minecraft.class_339.method_25394(class_339.java:67)
	at net.minecraft.class_437.method_25394(class_437.java:109)
	at fabric.org.figuramc.figura.gui.screens.AbstractPanelScreen.method_25394(AbstractPanelScreen.java:85)
	at net.minecraft.class_757.method_3192(class_757.java:1281)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.renderScrollBar(BackendMotdWidget.java:153)
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.renderDecorations(BackendMotdWidget.java:175)
	at fabric.org.figuramc.figura.gui.widgets.BackendMotdWidget.method_25359(BackendMotdWidget.java:106)
	at net.minecraft.class_339.method_25394(class_339.java:67)
	at net.minecraft.class_437.method_25394(class_437.java:109)
	at fabric.org.figuramc.figura.gui.screens.AbstractPanelScreen.method_25394(AbstractPanelScreen.java:85)

-- Screen render details --
Details:
	Screen name: fabric.org.figuramc.figura.gui.screens.WardrobeScreen
	Mouse location: Scaled: (279, 161). Absolute: (836.000000, 483.000000)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:1281)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Chamelllemon'/230, l='ClientLevel', x=40.79, y=67.00, z=80.82]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,66,96), Section: (at 0,2,0 in 4,4,6; chunk contains blocks 64,-64,96 to 79,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2114 game time, 2114 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:516)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1843529680 bytes (1758 MiB) / 3177185280 bytes (3030 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28010.45
	Virtual memory used (MB): 24966.99
	Swap memory total (MB): 11773.97
	Swap memory used (MB): 2172.52
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.21
		figura: Figura 0.1.2+1.18.2
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.6-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.6-figura
			org_java-websocket_java-websocket: Java-WebSocket 1.5.4
		firstperson: FirstpersonModel 2.2.3
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.5
		notenoughanimations: NotEnoughAnimations 1.6.0
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		paperdoll: PaperDoll 1.1.0-mc1.18
	Launched Version: fabric-loader-0.14.21-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Chamelllemon'/230, l='ServerLevel[New World]', x=40.79, y=67.00, z=80.82]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	OptiFine Version: OptiFine_1.18.2_HD_U_H6
	OptiFine Build: 20220313-160847
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 536.23
	OpenGlRenderer: NVIDIA GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.2
	OptiFine jar version: OptiFine_1.18.2_HD_U_H6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Nikita/curseforge/minecraft/Instances/hnngh/.optifine/OptiFine_1.18.2_HD_U_H6/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by UnlikePaladin** [comment]
known issue, fixed in the latest GitHub commits.

**Comment by Chamelllemon** [comment]
Same error also seems to appear on forge, and yes, I use newest 1.2.0. figura mod version in both fabric and forge cases

The game crashed whilst rendering screen
Error: java.lang.ArithmeticException: / by zero



[crash-2023-10-14_10.29.55-client.txt](https://github.com/FiguraMC/Figura/files/12903854/crash-2023-10-14_10.29.55-client.txt)

**Comment by KitCat962** [comment]
Figura doesnt have a 1.2.0 version. Are you from the future?
Also, join the discord and attempt it on 0.1.3-rc2 (latest prerelease version) and see if it still occurs

**Comment by Chamelllemon** [comment]
Alright, my bad, it was 0.1.2, and I guess I'll try. I fixed it once though, I just forgot how
Edit: It works les go! (Besides trying 0.1.3 I only added some mods that I'm sure didn't affect that (Minimap and healthbar mod))
